<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>deploysharp-modelfactory</AssemblyName>
    <RootNamespace>DeploySharp.ModelFactory.Cli</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DeploySharp.ModelFactory\DeploySharp.ModelFactory.csproj" />
  </ItemGroup>
</Project>
