<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
    <RestorePackagesWithLockFile>false</RestorePackagesWithLockFile>
    <AssemblyName>DeploySharp.ModelPack.Json.CleanConsumer</AssemblyName>
    <RootNamespace>DeploySharp.ModelPack.Json.CleanConsumer</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JYPPX.DeploySharp.ModelPack.Json" Version="2.0.0-alpha.1" />
  </ItemGroup>
</Project>
