<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="JYPPX.OpenCV.runtime.win-x64" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\DeploySharp.Backend.OpenCV\DeploySharp.Backend.OpenCV.csproj" />
    <Content Include="..\..\tests\assets\onnxruntime\classification.onnx" Link="classification.onnx" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
