<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>DeploySharpApp.Plugin.Abstractions</AssemblyName>
    <RootNamespace>DeploySharpApp.Plugin.Abstractions</RootNamespace>
    <PackageId>DeploySharpApp.Plugin.Abstractions</PackageId>
    <IsPackable>false</IsPackable>
    <UseDeploySharpProjectReferences>false</UseDeploySharpProjectReferences>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DeploySharpApp.Contracts\DeploySharpApp.Contracts.csproj" />
    <PackageReference Include="System.Text.Json" />
  </ItemGroup>
</Project>
