<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageVersion Include="MSTest.TestAdapter" Version="4.3.3" />
    <PackageVersion Include="MSTest.TestFramework" Version="4.3.3" />
    <PackageVersion Include="Microsoft.ML.OnnxRuntime" Version="1.28.0" />
    <PackageVersion Include="System.Text.Json" Version="10.0.10" />
    <PackageVersion Include="SixLabors.ImageSharp" Version="3.1.11" />
    <PackageVersion Include="LLamaSharp" Version="0.27.0" />
    <PackageVersion Include="LLamaSharp.Backend.Cpu" Version="0.27.0" />
    <PackageVersion Include="JYPPX.OpenCV.CSharp.API" Version="5.0.0-preview.1" />
    <PackageVersion Include="JYPPX.OpenCV.runtime.win-x64" Version="5.0.0-preview.1" />
    <PackageVersion Include="JYPPX.OpenVINO.CSharp.API" Version="3.3.0" />
    <PackageVersion Include="OpenVINO.runtime.win" Version="2026.2.1" />
    <PackageVersion Include="JYPPX.TensorRT.CSharp.API" Version="4.0.0" />
  </ItemGroup>
</Project>
