<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageVersion Include="MSTest.TestAdapter" Version="4.3.3" />
    <PackageVersion Include="MSTest.TestFramework" Version="4.3.3" />
    <PackageVersion Include="Microsoft.ML.OnnxRuntime" Version="1.28.0" />
    <PackageVersion Include="System.Text.Json" Version="10.0.10" />
    <PackageVersion Include="SixLabors.ImageSharp" Version="3.1.11" />
    <PackageVersion Include="JYPPX.DeploySharp.Core" Version="2.0.0-alpha.1" />
    <PackageVersion Include="JYPPX.DeploySharp.Extensibility" Version="2.0.0-alpha.1" />
    <PackageVersion Include="JYPPX.DeploySharp.LLM" Version="2.0.0-alpha.1" />
    <PackageVersion Include="JYPPX.DeploySharp.Backend.OnnxRuntime" Version="2.0.0-alpha.1" />
    <PackageVersion Include="JYPPX.DeploySharp.Backend.LlamaSharp" Version="2.0.0-alpha.1" />
    <PackageVersion Include="JYPPX.DeploySharp.Backend.OpenCV" Version="2.0.0-alpha.1" />
    <PackageVersion Include="JYPPX.DeploySharp.Backend.OpenVINO" Version="2.0.0-alpha.1" />
    <PackageVersion Include="JYPPX.DeploySharp.Backend.TensorRT" Version="2.0.0-alpha.1" />
    <PackageVersion Include="JYPPX.DeploySharp.ModelFactory" Version="2.0.0-alpha.1" />
    <PackageVersion Include="JYPPX.DeploySharp.ModelPack.Json" Version="2.0.0-alpha.1" />
    <PackageVersion Include="JYPPX.DeploySharp.Visual" Version="2.0.0-alpha.1" />
    <PackageVersion Include="JYPPX.DeploySharp.Visual.OpenCV" Version="2.0.0-alpha.1" />
    <PackageVersion Include="JYPPX.DeploySharp.Visual.TensorRT" Version="2.0.0-alpha.1" />
    <PackageVersion Include="LLamaSharp" Version="0.27.0" />
    <PackageVersion Include="LLamaSharp.Backend.Cpu" Version="0.27.0" />
    <PackageVersion Include="JYPPX.OpenCV.CSharp.API" Version="5.0.0-preview.1" />
    <PackageVersion Include="JYPPX.OpenCV.runtime.win-x64" Version="5.0.0-preview.1" />
    <PackageVersion Include="JYPPX.OpenVINO.CSharp.API" Version="3.3.1" />
    <PackageVersion Include="OpenVINO.runtime.win" Version="2026.2.1" />
    <PackageVersion Include="JYPPX.TensorRT.CSharp.API" Version="4.0.0" />
    <PackageVersion Include="JYPPX.TensorRT.CSharp.API.Runtime.win-x64.trt10.11.cuda12.9.cudnn9.22.Bridge" Version="4.0.0" />
  </ItemGroup>
</Project>
